### PR TITLE
update to submitted version

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by ctb** [comment]
do you want a review?

**Comment by mr-c** [comment]
No more reviews, thanks! :-)

**Comment by mr-c** [comment]
But it does need merging.

**Comment by ctb** [comment]
On Mon, Sep 21, 2015 at 03:37:44PM -0700, Michael R. Crusoe wrote:

> But it does need merging.

I'm confused :). Do you need me (or someone) to merge it because of
permissions issues, or because we're sticking with the 2-person rule
but w/o review?

**Comment by mr-c** [comment]
Permission issues

**Comment by ctb** [comment]
fixed - you should be able to merge.

**Comment by mr-c** [comment]
Thanks

**Pull request merged**
